# Generated by Django 5.0.6 on 2024-05-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_category_rename_comment_comment_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expensive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cheap',
            field=models.ManyToManyField(default=None, to='apps.cheap'),
        ),
        migrations.AddField(
            model_name='product',
            name='expensive',
            field=models.ManyToManyField(default=None, to='apps.expensive'),
        ),
    ]
