# Generated by Django 5.0.6 on 2024-05-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_cheap_expensive_product_cheap_product_expensive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cheap',
        ),
        migrations.RemoveField(
            model_name='product',
            name='expensive',
        ),
        migrations.DeleteModel(
            name='Cheap',
        ),
        migrations.DeleteModel(
            name='Expensive',
        ),
    ]
