# Generated by Django 5.0.6 on 2024-05-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_product_cheap_remove_product_expensive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Izohlar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Mahsulotlar'},
        ),
    ]
